### ISSUE TITLE
resizen van images in github README files

### ISSUE THREAD

**Issue by jorn600** [richelbilderbeek/Dojo#56]

**Comment by richelbilderbeek** [comment]
Je bedoelt zeker het Scratch plaatje op de eerste pagina :-) ?

![2017-06-09-161130_1600x1200_scrot](https://user-images.githubusercontent.com/2098230/26979219-565095c8-4d2e-11e7-8994-626f2f789604.png)

**Comment by jorn600** [comment]
nee, echt?


2017-06-09 16:12 GMT+02:00 Richel Bilderbeek <notifications@github.com>:

**Comment by richelbilderbeek** [comment]
Gedaan!
