### ISSUE TITLE
Code Tim

### ISSUE THREAD

**Issue by antonhensen** [richelbilderbeek/Dojo#57]
void setup()
{
  pinMode(A0, INPUT);
  pinMode(12, OUTPUT);
  pinMode(13, OUTPUT);   
  Serial.begin(9600); 
}

void loop()
{
  Serial.println(analogRead(A0));
  if (analogRead(A0) > 256)
  {
    digitalWrite(13,HIGH);
  }
  if (analogRead(A0) > 512)
  {
    digitalWrite(12,HIGH);
  }
  delay(100);
}

**Comment by richelbilderbeek** [comment]
Been displayed.
