### ISSUE TITLE
Hoe moeten die boogjes eigenlijk? 

### ISSUE THREAD

**Issue by dagmarhofman** [richelbilderbeek/Dojo#58]
void setup()
{
  size(600, 600);
}

void arcRechtsOnder(int x, int y) {
  arc(x, y, 50, 50, 0, HALF_PI);
}

void arcLinksOnder(int x, int y) {
  arc(x, y, 50, 50, HALF_PI, PI);
}

void arcLinksBoven(int x, int y) {
  arc(x, y, 50, 50, PI, PI + HALF_PI);
}

void arcRechtsBoven(int x, int y) {
  arc(x, y, 50, 50, PI + HALF_PI, TWO_PI);
}

void draw()
{
  noFill();
  background(255, 255, 255);
  stroke(0, 0, 255);

  int i = 0;
  int j = 0;
  for (i=0; i<600; i+=50) {
    for (j=0; j<600; j+=50) {
      arcLinksBoven(i, j);
      arcRechtsOnder(i, j);
    }
  } 
  for (i=50; i<600; i+=150) {
    for (j=50; j<600; j+=150) {
      arcLinksOnder(i, j);
      arcRechtsBoven(i, j);
    }
  }
}

**Comment by richelbilderbeek** [comment]
1. Code omsluiten met drie backticks voor en na de code, met de backticks op een eigen regel
2. In Processing kun je met CTRL-Tde layout laten doen

**Comment by richelbilderbeek** [comment]
Old.
