### ISSUE TITLE
Jesper claims the OR from 201.txt should be reflected in all_needed_to_slay_zanbar_bone in 156.txt (and elsewhere)

### ISSUE THREAD

**Issue by wdoekes** [richelbilderbeek/Dojo#65]
Hi! See subject.

Speed-running the game is not possible if you're required to fetch useless items. Consider making it a user-made choice instead? So the player can decide for himself whether he has enough items.

Cheers, and thanks for the game!

**Comment by wdoekes** [comment]
Oops. Wrong repo :)

**Comment by richelbilderbeek** [comment]
No problemo :rainbow:
